### ISSUE TITLE
Crash Report - Unable to Understand

### ISSUE THREAD

**Issue by Symphoney** [Azmalent/terra-incognita#31] opened 2021-03-13 20:18 UTC
So, this is causing my server plenty of Ticking Entity crashes - https://pastebin.com/tTbNAb2i

Any idea what's going on? Is it conflicting with other mods?

**Comment by Symphoney** [comment] 2021-03-13 20:24
Every time I try to join my server, it crashes, so I'm not sure what's going on

**Comment by Azmalent** [comment] 2021-03-13 20:26
Duplicate of #30. It's a known issue with butterflies that will be fixed in 1.6.1, I'm almost done with the update right now.

**Closed by Azmalent** 2021-03-13 20:26 UTC
