### ISSUE TITLE
[1.18.2] Game crashes on startup with new 1.18 beta

### ISSUE THREAD

**Issue by NJL5390** [Azmalent/terra-incognita#56] opened 2022-06-15 17:24 UTC
Terra Incognita version: 2.0-BETA
Terrablender Version: 1.1.0.102
Cuneiform Version: 1.3.1
Forge Version: 40.1.51
Crash Report: https://gist.github.com/NJL5390/561cc7d42628592b99618ac78fe4eae6

Hi there!

Just letting you know that I've run into a crash on startup whenever I attempt to test the 1.18 beta version of this mod. This issue is reproducible with only the required dependencies. 

I really loved the 1.16.5 version of this mod, it always felt like this mod filled a niche that I never knew was there, so I'm very much looking forward to seeing what content you add to the 1.18 version!

Thanks!

**Comment by Azmalent** [comment] 2022-06-15 21:28
It was indeed an issue with newer forge versions. Just uploaded the second beta, should fix the problem!

**Comment by NJL5390** [comment] 2022-06-15 22:20
Alright, So this particular issue described in the crash report above seems to be fixed! 

The mod still seems to crash if I try and load it with other mods though, I think the log mentioned something about farmer's delight compatibility being broken? It's between lines 291 and 310 is where the log mentions it.

Here's the full log: https://gist.github.com/NJL5390/9293c970eea4467e0bbb16111357f32a

Oddly enough a crash report isn't generated for this crash so I can't provide one.

I know that you mentioned mod compat was something you'd be working on later but I just thought I'd mention the crash here so that you know about it and can address it whenever it suits you.

Thanks for your help with the first crash though!

**Comment by Azmalent** [comment] 2022-06-15 23:08
Oof. Okay, beta 3 should fix this one.

**Comment by NJL5390** [comment] 2022-06-16 07:49
Ok, So the farmer's delight issue seems to be addressed, however I have unfortunately come across another issue relating to a mixin for compatibility with quark.

Here's the crash report for this one: https://gist.github.com/NJL5390/a3a6a663cafa0f6944e72db46c8e88ee

I hate to be the bearer of bad news, so I really hope there's no more after this, sorry for bothering you with these issues.

**Comment by Azmalent** [comment] 2022-06-16 08:28
Closing as the Quark issue is a duplicate of #57.
Thanks for all the bug reports! :)

**Closed by Azmalent** 2022-06-16 08:28 UTC
