### ISSUE TITLE
interacting with the Cupboard Inventory is Crashing the Game

### ISSUE THREAD

**Issue by Morabert** [Azmalent/terra-incognita#44] opened 2021-07-23 17:34 UTC
[crash-2021-07-23_19.25.57-client.txt](https://github.com/Azmalent/terra-incognita/files/6870318/crash-2021-07-23_19.25.57-client.txt)

**Comment by Morabert** [comment] 2021-07-23 17:46
It did it again, this time with a chest
[crash-2021-07-23_19.42.32-client.txt](https://github.com/Azmalent/terra-incognita/files/6870392/crash-2021-07-23_19.42.32-client.txt)

**Comment by Morabert** [comment] 2021-07-24 12:42
It seems it may in fact crashing when interacting with either be Apple Chests, or Baskets, or Both:
The game crashed whilst rendering screen
Error: java.lang.AbstractMethodError: Method azmalent/terraincognita/common/integration/quark/BasketDropIn.canDropItemIn(Lnet/minecraft/entity/player/PlayerEntity;Lnet/minecraft/item/ItemStack;Lnet/minecraft/item/ItemStack;Lnet/minecraft/inventory/container/Slot;)Z is abstract
Exit Code: -1
[debug.log](https://github.com/Azmalent/terra-incognita/files/6872406/debug.log)

**Comment by Azmalent** [comment] 2021-08-21 19:12
Duplicate of #40, this bug was fixed in the new beta.

**Closed by Azmalent** 2021-08-21 19:12 UTC
Labels: duplicate
