### ISSUE TITLE
[1.18.2]Crash in generated worlds when used with TeamAbnormals' mods

### ISSUE THREAD

**Issue by ALONEJINGYAN** [Azmalent/terra-incognita#77] opened 2023-02-07 17:53 UTC
Description: Exception generating new chunk

Generated worlds crash when Terra Incognita: The Unknown Land is used in conjunction with Abnormals' mods
When I delete Terra Incognita: The Unknown Land it works fine

[https://github.com/ALONEJINGYAN/crash-2023-02-08_01.29.34-server/blob/10cc0c31d9fa1ada51658ac59cacd866c84948f7/crash-2023-02-08_01.29.34-server.txt](url)

terraincognita-1.18.2-2.0.1
blueprint-1.18.2-5.5.0
abnormals_delight-1.18.2-3.0.2
atmospheric-1.18.2-4.0.0
autumnity-1.18.2-3.0.0
environmental-1.18.2-2.0.0
upgrade_aquatic-1.18.2-4.0.0
woodworks-1.18.2-1.1.0

The same problem occurs when using with projectvibrantjourneys
projectvibrantjourneys-1.18.2-4.1.1

**Comment by Azmalent** [comment] 2024-03-23 10:49
Closing as a duplicate of #76

**Closed by Azmalent** 2024-03-23 10:49 UTC
Labels: duplicate
